name: Docker Image CI

on:
  push:
    branches: [ "stage", "main" ]
  pull_request:
    branches: [ "stage", "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Run one line script
      run: echo Hello, World
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag notesServer:$(date +%s)
