name: Docker Image CI

on:
  push:
    branches: [ "stage", "main" ]
  pull_request:
    branches: [ "stage", "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make -C ./build

    - name: Run check
      run: echo make check -C ./build
  
  test:

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: start tests
        run: sleep 20s
  
  docker:

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: ls step
      run: ls
    - name: pwd step
      run: pwd
    - name: Run one line script
      run: echo Hello, World
    - name: Build the Docker image
      run: docker build ./build --tag notesserver:$(date +%s)
