name: Docker Image CI

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22.2"
    - name: Install dependencies
      run: |
        ls -l
        pwd
        echo needed dependencies

    - name: Install dependencies
      run: make -C ./build

    - name: Run check
      run: echo make check -C ./build
  
  test:

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: start tests
        run: sleep 20s
  
  docker:

    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: ls step
      run: ls
    - name: pwd step
      run: pwd
    - name: Run one line script
      run: echo Hello, World
    - name: Build the Docker image
      run: docker build . --tag notesserver:v1
