name: Makefile CI

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [ "main", "stage" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: make -C ./build

    - name: Run check
      run: echo make check -C ./build

