name: Build 

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up go
      uses: actions/setup-go@v5
      with:
        cache: false
        go-version: "1.22.2"

    - name: Install dependencies
      run: |
        ls -l
        pwd
        echo needed dependencies

    - name: Build app
      run: make -C ./build

    - name: Run check
      run: echo make check -C ./build

    - name: start tests
      run: sleep 10s
    
